#!/usr/bin/env python3
"""Find data fields the renderer never reads, and stale symbols in the universe.

Two audits that each caught real defects and are worth repeating:

1. UNRENDERED FIELDS. Writing a field to JSON feels like publishing it. Nothing
   errors, the file validates, and the page looks complete because you do not miss
   a block you never saw. This has happened at least four times in this repo —
   `scope` on a policy regime, `data_caveat` on six companies (including the most
   policy-exposed name in the book), `impact` on all eight regimes, and `date_note`
   on four levers. Each was written deliberately, by someone who believed a reader
   would see it.

2. STALE SYMBOLS. A delisted instrument does not leave the price feed. The provider
   keeps serving old history and pads a null bar at today's timestamp, so the last
   row looks current. Two dead tickers were being shown as live prices before this
   check existed.

Neither audit runs in CI — (1) is advisory and needs a human to say which fields
are intentionally internal, and (2) needs network. Run them when touching the
schema or the universe.

    python3 scripts/audit_schema.py            # unrendered-field sweep
    python3 scripts/audit_schema.py --symbols  # add the network staleness sweep
"""
import glob
import json
import os
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Generated by the pipeline and rendered through their own builders, where a
# per-field grep gives only false positives.
GENERATED = {
    "quotes.json", "indices.json", "news.json", "alerts.json", "performance.json",
    "breaking.json", "calendar.json", "trends.json", "trends-wm.json", "metrics.json",
}

# Structural or documentation keys that are not meant to reach the page.
SKIP_FIELDS = {"_meta", "description", "note", "as_of", "fields", "url", "id"}

# Reviewed and deliberately internal: sort keys, colour tokens, join keys. Listed
# explicitly so the sweep stays quiet about them and LOUD about anything new.
KNOWN_INTERNAL = {
    ("companies.json", "last_reviewed"), ("companies.json", "provisional"),
    ("companies.json", "source_note"), ("companies.json", "source_screen"),
    ("critical-minerals.json", "group"), ("critical-minerals.json", "sym"),
    ("matrix.json", "ids"),
    ("policy.json", "status_color"), ("policy.json", "date_iso"),
    ("policy.json", "date_unresolved"), ("portfolio.json", "cats"),
}


def sweep_fields():
    html = (ROOT / "index.html").read_text()
    findings, reviewed = [], 0
    for f in sorted(glob.glob(str(ROOT / "data" / "*.json"))):
        base = os.path.basename(f)
        if base in GENERATED:
            continue
        doc = json.load(open(f))
        if not isinstance(doc, dict):
            continue
        for _key, arr in doc.items():
            if not (isinstance(arr, list) and arr and isinstance(arr[0], dict)):
                continue
            counts = {}
            for rec in arr:
                for k in rec:
                    counts[k] = counts.get(k, 0) + 1
            for k, n in sorted(counts.items()):
                if k in SKIP_FIELDS:
                    continue
                reviewed += 1
                # `.field`, ['field'] or "field" anywhere in the renderer
                if re.search(r'[.\[]\s*[\'"]?' + re.escape(k) + r'\b', html):
                    continue
                findings.append((base, k, n, (base, k) in KNOWN_INTERNAL))

    new = [x for x in findings if not x[3]]
    known = [x for x in findings if x[3]]
    print(f"Field sweep — {reviewed} field/file pairs checked against index.html\n")
    if new:
        print(f"  {len(new)} field(s) NOT rendered and NOT on the reviewed-internal list:")
        for base, k, n, _ in new:
            print(f"    {base:<26} {k:<22} {n:>4} record(s)")
        print("\n  Each is either a field a reader should see, or one to add to"
              "\n  KNOWN_INTERNAL in this script with a reason.")
    else:
        print("  No unreviewed unrendered fields.")
    if known:
        print(f"\n  ({len(known)} reviewed-internal field(s) skipped.)")
    return 1 if new else 0


def sweep_symbols():
    try:
        import yfinance as yf
    except ImportError:
        print("\nSymbol sweep skipped — yfinance not installed", file=sys.stderr)
        return 0
    sys.path.insert(0, str(ROOT / "scripts"))
    from fetch_market import load_companies, yahoo_symbol

    comps = load_companies()
    tks = [c["ticker"] for c in comps]
    ymap = {t: yahoo_symbol(t) for t in tks}
    print(f"\nSymbol sweep — {len(tks)} tickers, 3mo of history\n")
    hist = yf.download(sorted(set(ymap.values())), period="3mo", auto_adjust=True,
                       progress=False, group_by="ticker", threads=True)
    today, bad = date.today(), []
    for t in tks:
        y = ymap[t]
        try:
            d = hist[y] if y in hist.columns.get_level_values(0) else None
            if d is None:
                bad.append((t, None, "no column in the feed"))
                continue
            # Staleness from the last NON-NULL close: the padded bar at today's
            # timestamp is what makes a dead ticker look alive.
            c = d["Close"].dropna()
            if not len(c):
                bad.append((t, None, "no non-null closes"))
                continue
            age = (today - c.index[-1].date()).days
            if age > 7:
                bad.append((t, age, f"last close {c.index[-1].date()}"))
        except Exception as e:
            bad.append((t, None, str(e)[:40]))

    if bad:
        print(f"  {len(bad)} ticker(s) stale over 7 days or missing:")
        for t, age, why in sorted(bad, key=lambda r: -(r[1] or 999)):
            print(f"    {t:<12} {('age ' + str(age) + 'd') if age else 'missing':<12} {why}")
        print("\n  A stale ticker is usually a MIGRATION, not a death — check for a new"
              "\n  listing before doing anything. Correct the symbol, then RUN A FULL PASS:"
              "\n  generated files keep the old symbol until they are rebuilt.")
    else:
        print("  No stale or missing symbols.")
    return 1 if bad else 0


if __name__ == "__main__":
    rc = sweep_fields()
    if "--symbols" in sys.argv:
        rc |= sweep_symbols()
    sys.exit(rc)
